ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=2D0)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MH,MDL_MTA,MDL_MZ,MDL_MB

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MH,MDL_MTA,MDL_MZ,MDL_MB


      DOUBLE PRECISION MDL_WT,MDL_WH,MDL_WZ,MDL_WW

      COMMON/WIDTHS/ MDL_WT,MDL_WH,MDL_WZ,MDL_WW


      DOUBLE COMPLEX GC_1, GC_3, GC_50, GC_58, GC_59

      COMMON/COUPLINGS/ GC_1, GC_3, GC_50, GC_58, GC_59

