# PYTHIA configuration file.
# Generated on Wed Jun 2 11:50:47 EDT 2021 with the user supplied options:
# --prefix=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/pythia8/
# --with-hepmc2=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/hepmc
# --with-hepmc2-include=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/hepmc/include
# --with-gzip=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/zlib
# --cxx-common='-ldl -fPIC -lstdc++ -DHEPMC2HACK'

# Install directory prefixes.
PREFIX_BIN=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/pythia8//bin
PREFIX_INCLUDE=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/pythia8//include
PREFIX_LIB=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/pythia8//lib
PREFIX_SHARE=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/pythia8//share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-ldl -fPIC -lstdc++ -DHEPMC2HACK
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=
FASTJET3_LIB=

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/hepmc/bin
HEPMC2_INCLUDE=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/hepmc/include
HEPMC2_LIB=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/hepmc/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=

# LHAPDF6 configuration.
LHAPDF6_USE=false
LHAPDF6_BIN=
LHAPDF6_INCLUDE=
LHAPDF6_LIB=

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=false
ROOT_BIN=
ROOT_LIBS=
CXX_ROOT=

# GZIP configuration.
GZIP_USE=true
GZIP_BIN=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/zlib/
GZIP_INCLUDE=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/zlib/include
GZIP_LIB=/het/p4/mjw283/eventgen_wd/MG5_aMC_v3_1_0/HEPTools/zlib/lib

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=
BOOST_LIB=

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=
PYTHON_LIB=
